const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),panel=document.querySelector('#panel'),overlay=document.querySelector('#overlay');
const colors=['#b6f36e','#a49bff','#ffad73','#75dfff'],controls=[['w','s','a','d'],['arrowup','arrowdown','arrowleft','arrowright'],['i','k','j','l'],['t','g','f','h']],labels=['W A S D','↑ ← ↓ →','I J K L','T F G H'];
let players=[],items=[],keys=new Set(),round=0,remaining=20,state='setup',last=0,particles=[];
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scoreboard(){document.querySelector('#players').innerHTML=players.map((p,i)=>`<div class="player"><div><span class="dot" style="background:${colors[i]}"></span>${escapeHtml(p.name)}<small>${labels[i]} · ${p.history.join(' / ')||'Ready'}</small></div><span class="score">${p.score}</span></div>`).join('');document.querySelector('#rounds').innerHTML=[1,2,3,4].map(n=>`<span class="${n===round?'active':''}">${n}</span>`).join('');}
function setup(){state='setup';keys.clear();round=0;players=[];items=[];document.querySelector('#pause').disabled=true;document.querySelector('#round').textContent='READY TO RUSH';document.querySelector('#timer').textContent='20 seconds / round';overlay.classList.remove('hidden');panel.innerHTML='<span class="tag">GET YOUR CREW</span><h2>Enter the arena</h2><p><b>Both players play at the same time!</b><br><span style="color:#b6f36e">Player 1: W ↑ · A ← · S ↓ · D →</span><br><span style="color:#a49bff">Player 2: Arrow keys ↑ ← ↓ →</span><br>Hold your keys to move. Collect gems during four shared 20-second rounds.</p><label>Number of players <select id="count"><option>2</option><option>3</option><option>4</option></select></label><div class="names" id="names"></div><button class="primary" id="start">Let’s rush →</button><p style="font-size:12px">One shared keyboard · Press Escape to pause</p>';const names=()=>{document.querySelector('#names').innerHTML=Array.from({length:+document.querySelector('#count').value},(_,i)=>`<label>Player ${i+1} · ${labels[i]}<input maxlength="18" id="name${i}" value="Player ${i+1}" aria-label="Player ${i+1} name"></label>`).join('')};names();document.querySelector('#count').onchange=names;document.querySelector('#start').onclick=()=>{players=Array.from({length:+document.querySelector('#count').value},(_,i)=>({name:document.querySelector('#name'+i).value.trim()||'Player '+(i+1),score:0,history:[],x:0,y:0}));startRound()};scoreboard();}
function spawn(type){for(let tries=0;tries<100;tries++){const item={x:35+Math.random()*730,y:35+Math.random()*450,type};if(items.every(a=>Math.hypot(a.x-item.x,a.y-item.y)>38)&&players.every(p=>Math.hypot(p.x-item.x,p.y-item.y)>50)){items.push(item);return}}}
function startRound(){round++;remaining=20;players.forEach((p,i)=>{p.x=i%2?740:60;p.y=i<2?60:460;p.before=p.score});items=[];particles=[];for(let i=0;i<18;i++)spawn('gem');for(let i=0;i<3;i++)spawn('gold');for(let i=0;i<4+round;i++)spawn('trap');state='playing';keys.clear();last=performance.now();overlay.classList.add('hidden');document.querySelector('#pause').disabled=false;document.querySelector('#pause').textContent='Pause';scoreboard();}
function endRound(){state=round===4?'finished':'between';keys.clear();document.querySelector('#pause').disabled=true;players.forEach(p=>p.history.push(p.score-p.before));scoreboard();overlay.classList.remove('hidden');const best=Math.max(...players.map(p=>p.score)),winners=players.filter(p=>p.score===best).map(p=>escapeHtml(p.name));panel.innerHTML=round===4?`<span class="tag">FINAL RESULTS</span><h2>${winners.join(' &amp; ')} ${winners.length>1?'share the crown!':'wins!'}</h2><p>${best} points after four rounds. Well played.</p><button class="primary" id="next">Play again →</button>`:`<span class="tag">ROUND ${round} COMPLETE</span><h2>Catch your breath.</h2><p>${winners.join(' &amp; ')} ${winners.length>1?'are':'is'} leading with ${best} points.<br>Next round brings more traps.</p><button class="primary" id="next">Start round ${round+1} →</button>`;document.querySelector('#next').onclick=round===4?setup:startRound;}
function pause(){if(!['playing','paused'].includes(state))return;keys.clear();if(state==='playing'){state='paused';overlay.classList.remove('hidden');panel.innerHTML='<h2>Rush on hold</h2><p>The timer is paused. Ready when you are.</p><button class="primary" id="resume">Resume →</button>';document.querySelector('#resume').onclick=pause;document.querySelector('#pause').textContent='Resume'}else{state='playing';last=performance.now();overlay.classList.add('hidden');document.querySelector('#pause').textContent='Pause'}}
document.querySelector('#pause').onclick=pause;document.querySelector('#restart').onclick=()=>{if(state==='setup'||state==='finished'||confirm('End this match and start a new game?'))setup()};window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(controls.flat().includes(k)&&state!=='setup'){e.preventDefault();keys.add(k)}if(k==='escape'&&!e.repeat)pause()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause()});
function update(dt){remaining=Math.max(0,remaining-dt);players.forEach((p,i)=>{let [up,down,left,right]=controls[i],dx=+keys.has(right)-+keys.has(left),dy=+keys.has(down)-+keys.has(up),len=Math.hypot(dx,dy)||1;p.x=Math.max(16,Math.min(784,p.x+dx/len*210*dt));p.y=Math.max(16,Math.min(504,p.y+dy/len*210*dt));for(let j=items.length-1;j>=0;j--){let a=items[j];if(Math.hypot(a.x-p.x,a.y-p.y)<24){let delta=a.type==='gold'?25:a.type==='gem'?10:-10;p.score=Math.max(0,p.score+delta);particles.push({x:a.x,y:a.y,text:delta>0?'+'+delta:''+delta,life:0.8,color:colors[i]});items.splice(j,1);spawn(a.type);scoreboard()}}});particles.forEach(p=>{p.life-=dt;p.y-=dt*35});particles=particles.filter(p=>p.life>0);document.querySelector('#round').textContent=`ROUND ${round} / 4`;document.querySelector('#timer').textContent=`${Math.ceil(remaining)}s`;if(remaining<=0)endRound()}
function draw(){ctx.fillStyle='#121a2e';ctx.fillRect(0,0,800,520);ctx.strokeStyle='#1e2942';ctx.lineWidth=1;for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,520);ctx.stroke()}for(let y=0;y<520;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(800,y);ctx.stroke()}items.forEach(a=>{ctx.save();ctx.translate(a.x,a.y);ctx.fillStyle=a.type==='gold'?'#ffd477':a.type==='trap'?'#ff7e99':'#b6f36e';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;if(a.type==='trap'){ctx.rotate(Math.PI/4);ctx.fillRect(-10,-3,20,6);ctx.fillRect(-3,-10,6,20)}else{ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(9,0);ctx.lineTo(0,11);ctx.lineTo(-9,0);ctx.closePath();ctx.fill()}ctx.restore()});players.forEach((p,i)=>{ctx.fillStyle=colors[i];ctx.shadowColor=colors[i];ctx.shadowBlur=18;ctx.beginPath();ctx.arc(p.x,p.y,14,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#172136';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.fillText(i+1,p.x,p.y+5)});particles.forEach(p=>{ctx.globalAlpha=p.life/0.8;ctx.fillStyle=p.color;ctx.font='bold 20px system-ui';ctx.fillText(p.text,p.x,p.y)});ctx.globalAlpha=1;}
function frame(now){const dt=Math.min((now-last)/1000,0.05);last=now;if(state==='playing')update(dt);draw();requestAnimationFrame(frame)}setup();requestAnimationFrame(frame);
